// 疫苗管理设置卡：疫苗目录列表、编辑器（由 Settings.tsx 抽出，逻辑不变）
import { useState } from 'react';
import { api } from '../../api';
import { confirmAction, ActionMenu, Modal, SegmentedControl, Switch, useDirtyClose } from '../../ui';
import { Feedback } from './Feedback';
import type { DraftVaccineCatalogItem, VaccineCatalogItem } from '../../types';

export function VaccineCatalogEditor({ item, onClose, onSaved }: { item?: VaccineCatalogItem; onClose(): void; onSaved(item: VaccineCatalogItem): void }) {
  const initial: DraftVaccineCatalogItem = { name: item?.name || '', category: item?.category || 'program', shortName: item?.shortName ?? null, description: item?.description || '', doseCount: item?.doseCount ?? 1, intervalSummary: item?.intervalSummary || '' };
  const [draft, setDraft] = useState(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const dirty = JSON.stringify(draft) !== JSON.stringify(initial);
  const requestClose = useDirtyClose(dirty, onClose, busy, { title: '放弃未保存的修改？', description: '疫苗信息尚未保存。' });
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setBusy(true); setError('');
    const payload = { ...draft, name: draft.name.trim(), description: draft.description.trim(), intervalSummary: draft.intervalSummary.trim() };
    try { const saved = item ? await api.updateVaccineCatalogItem(item.id, payload) : await api.createVaccineCatalogItem(payload); onSaved(saved); onClose(); }
    catch (err) { setError(err instanceof Error ? err.message : '保存疫苗失败'); setBusy(false); }
  }
  return <Modal className="vaccine-catalog-editor" title={item ? '修改疫苗' : '新增疫苗'} kicker="疫苗目录" onClose={() => void requestClose()}><form className="editor-form" onSubmit={submit}><label>疫苗名称<input value={draft.name} maxLength={50} required autoFocus={!item} placeholder="例如：水痘疫苗" onChange={event => setDraft(value => ({ ...value, name: event.target.value }))} /></label><fieldset><legend>疫苗类型</legend><SegmentedControl label="疫苗类型" value={draft.category} options={[{ value: 'program', label: '规划' }, { value: 'self_paid', label: '自费' }]} onChange={category => setDraft(value => ({ ...value, category }))} /></fieldset><label>常规剂次<select value={draft.doseCount ?? ''} onChange={event => setDraft(value => ({ ...value, doseCount: event.target.value ? Number(event.target.value) : null }))}><option value="">按接种门诊安排</option>{Array.from({ length: 9 }, (_, index) => <option value={index + 1} key={index + 1}>{index + 1} 剂</option>)}</select></label><label>预防疾病 <span>选填</span><textarea rows={3} maxLength={300} value={draft.description} placeholder="例如：用于预防水痘。" onChange={event => setDraft(value => ({ ...value, description: event.target.value }))} /></label><label>接种程序 <span>选填</span><textarea rows={2} maxLength={200} value={draft.intervalSummary} placeholder="例如：共 2 剂，每剂至少间隔 3 个月" onChange={event => setDraft(value => ({ ...value, intervalSummary: event.target.value }))} /></label>{error && <Feedback message={error} type="error" onClose={() => setError('')} />}<footer className="editor-actions"><button type="button" className="btn secondary" disabled={busy} onClick={() => void requestClose()}>取消</button><button className="btn primary" disabled={busy || !draft.name.trim()}>{busy ? '保存中…' : '保存疫苗'}</button></footer></form></Modal>;
}

export function VaccineSettingsCard({ catalog, manager, onCatalogChanged }: { catalog: VaccineCatalogItem[]; manager: boolean; onCatalogChanged(): Promise<void> }) {
  const [busy, setBusy] = useState(''); const [expanded, setExpanded] = useState(''); const [editing, setEditing] = useState<VaccineCatalogItem | 'new' | null>(null); const [message, setMessage] = useState<{ text: string; error?: boolean } | null>(null);
  async function toggle(item: VaccineCatalogItem) { setBusy(item.id); setMessage(null); try { await api.setVaccineCatalogActive(item.id, !item.active); await onCatalogChanged(); setMessage({ text: item.active ? `${item.name}已停用` : `${item.name}已启用` }); } catch (error) { setMessage({ text: error instanceof Error ? error.message : '更新疫苗目录失败', error: true }); } finally { setBusy(''); } }
  async function remove(item: VaccineCatalogItem) { if (!await confirmAction({ title: `删除“${item.name}”？`, description: '将从疫苗目录和未来接种安排中移除；已接种历史记录仍会保留。', confirmLabel: '删除疫苗', danger: true })) return; setBusy(item.id); setMessage(null); try { await api.deleteVaccineCatalogItem(item.id); await onCatalogChanged(); setExpanded(current => current === item.id ? '' : current); setMessage({ text: `${item.name}已删除` }); } catch (error) { setMessage({ text: error instanceof Error ? error.message : '删除疫苗失败', error: true }); } finally { setBusy(''); } }
  return <><section className="settings-card vaccine-settings-card"><div><h2>疫苗提醒</h2><p>首页自动显示近期建议接种与门诊预约，无需单独开启。</p></div><dl><div><dt>提醒依据</dt><dd>预约日期优先</dd></div><div><dt>参考规则</dt><dd>国家免疫规划（2021年版）</dd></div></dl><p className="vaccine-safety-note">门诊没有给出预约时无需设置。系统建议日期仅供参考。</p></section>
  <section className="settings-card vaccine-catalog-card"><div className="section-title"><div><h2>疫苗目录</h2></div><div className="catalog-head-actions"><span>{catalog.filter(item => item.active).length} 项启用</span></div></div><p>内置 10 种默认疫苗只能启用或停用；自行新增的疫苗可以修改和删除。</p><div className="vaccine-catalog-list">{catalog.map(item => <article key={item.id} className={`${item.active ? '' : 'inactive'} ${manager ? '' : 'readonly'}`}><div className="catalog-copy"><div className="catalog-title"><b>{item.name}</b><i className={`vaccine-kind ${item.category}`}>{item.category === 'program' ? '规划' : '自费'}</i></div><small>{item.doseCount ? `${item.doseCount} 剂` : '按接种门诊安排'}{item.isSystem ? ' · 系统默认' : ''}</small></div>{manager && !item.isSystem ? <ActionMenu label={`管理${item.name}`} items={[{ label: expanded === item.id ? '收起详情' : '查看详情', onSelect: () => setExpanded(expanded === item.id ? '' : item.id) }, { label: '修改', onSelect: () => setEditing(item) }, { label: '删除', danger: true, onSelect: () => remove(item) }]} /> : <button type="button" className="catalog-detail-toggle" aria-expanded={expanded === item.id} onClick={() => setExpanded(expanded === item.id ? '' : item.id)}>{expanded === item.id ? '收起' : '详情'}</button>}{manager && <Switch checked={item.active} label={`${item.active ? '停用' : '启用'}${item.name}`} disabled={Boolean(busy)} onChange={() => void toggle(item)} />}{expanded === item.id && <div className="catalog-detail"><dl><dt>预防疾病</dt><dd>{item.description || '尚未填写。'}</dd><dt>接种程序</dt><dd>{item.intervalSummary || (item.doseCount ? `共 ${item.doseCount} 剂` : '按接种门诊安排')}</dd></dl></div>}</article>)}</div>{manager && <button type="button" className="btn primary full" disabled={Boolean(busy)} onClick={() => setEditing('new')}>新增疫苗</button>}<Feedback message={message?.text || ''} type={message?.error ? 'error' : 'success'} onClose={() => setMessage(null)} /></section>{editing && <VaccineCatalogEditor item={editing === 'new' ? undefined : editing} onClose={() => setEditing(null)} onSaved={async saved => { await onCatalogChanged(); setMessage({ text: editing === 'new' ? `${saved.name}已新增` : `${saved.name}已修改` }); }} />}</>;
}
